---
- name: Copy .bashrc to target
  copy:
    src: "{{ role_path }}/templates/.bashrc.j2"
    dest: "/home/{{ ansible_user }}/.bashrc"
    
- name: Copy .vimrc to target
  copy: 
    src: "{{ role_path }}/templates/.vimrc.j2"
    dest: "/home/{{ ansible_user }}/.vimrc"